send:
  description: Send a raw packet to device.
  fields:
    host: {description: IP address of device to send packet via. This must be an already configured device., example: "192.168.0.1"}
    packet: {description: base64 encoded packet.}
learn:
  description: Learn a IR or RF code from remote.
  fields:
    host: {description: IP address of device to send packet via. This must be an already configured device., example: "192.168.0.1"}
